FROM python:3.9-slim

WORKDIR /app

COPY requirements-frontend.txt requirements-frontend.txt

RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY . .

EXPOSE 7860

CMD ["python", "frontend/app.py"]