FROM python:3.9-slim

WORKDIR /app

COPY requirements-api.txt requirements-api.txt

RUN pip install --no-cache-dir -r requirements-api.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]